/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanLiKho.GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanLiKho.BLL.*;
import quanLiKho.DTO.LoaiSPDTO;
import quanLiKho.DTO.MauSacDTO;
import quanLiKho.DTO.SizeDTO;

/**
 *
 * @author PC
 */
public class ThuocTinhGUI extends javax.swing.JPanel {
    private LoaiSPBLL loaiBLL = new LoaiSPBLL();
    private MauSacBLL mauBLL = new MauSacBLL();
    private SizeBLL sizeBLL = new SizeBLL();
    private DefaultTableModel model_loai, model_mau, model_size;
    
    private String tenDN;
    private static int soLoai, soMau, soSize;
    
    public ThuocTinhGUI(String tenDN) {
        this.soLoai = loaiBLL.getSelectedAll().size();
        this.soMau = mauBLL.getSelectedAll().size();
        this.soSize = sizeBLL.getSelectedAll().size();
        this.tenDN = tenDN;
        model_loai  = (DefaultTableModel) tb_loai.getModel();
        model_mau  = (DefaultTableModel) tb_mau.getModel();
        model_size  = (DefaultTableModel) tb_size.getModel();
        docDuLieuLoaiSP(); docDuLieuMau(); docDuLieuSize();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_loai = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_size = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_mau = new javax.swing.JTable();
        jp_button = new javax.swing.JPanel();
        jb_timkiem = new javax.swing.JButton();
        jb_xoa = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cb_timkiem = new javax.swing.JComboBox<>();
        tf_timkiem = new javax.swing.JTextField();
        jb_them = new javax.swing.JButton();
        jb_xemtatca = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1640, 940));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loại sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        tb_loai.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        tb_loai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại", "Tên loại"
            }
        ));
        tb_loai.setRowHeight(35);
        jScrollPane1.setViewportView(tb_loai);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Size", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        tb_size.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        tb_size.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã size", "Tên size"
            }
        ));
        tb_size.setRowHeight(35);
        jScrollPane5.setViewportView(tb_size);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Màu sắc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        tb_mau.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        tb_mau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã màu sắc", "Tên màu sắc"
            }
        ));
        tb_mau.setRowHeight(35);
        jScrollPane4.setViewportView(tb_mau);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jp_button.setBackground(new java.awt.Color(255, 255, 255));

        jb_timkiem.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jb_timkiem.setText("Tìm kiếm");
        jb_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_timkiemActionPerformed(evt);
            }
        });

        jb_xoa.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jb_xoa.setText("Xoá thuộc tính");
        jb_xoa.setPreferredSize(new java.awt.Dimension(171, 40));
        jb_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_xoaActionPerformed(evt);
            }
        });

        cb_timkiem.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        cb_timkiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại sản phẩm", "Màu sắc", "Kích thước" }));
        cb_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_timkiemActionPerformed(evt);
            }
        });

        tf_timkiem.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N

        jb_them.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jb_them.setText("Thêm thuộc tính");
        jb_them.setPreferredSize(new java.awt.Dimension(185, 40));
        jb_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_themActionPerformed(evt);
            }
        });

        jb_xemtatca.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jb_xemtatca.setText("Xem tất cả");
        jb_xemtatca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_xemtatcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_buttonLayout = new javax.swing.GroupLayout(jp_button);
        jp_button.setLayout(jp_buttonLayout);
        jp_buttonLayout.setHorizontalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addGap(1164, 1164, 1164)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(cb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jb_timkiem)
                .addGap(48, 48, 48)
                .addComponent(jb_xemtatca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jp_buttonLayout.setVerticalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_buttonLayout.createSequentialGroup()
                        .addGroup(jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141)
                        .addComponent(jLabel18))
                    .addGroup(jp_buttonLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_xemtatca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jp_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_timkiemActionPerformed

    private void jb_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_themActionPerformed
        String loaitk = (String) cb_timkiem.getSelectedItem();
        String text = (String) tf_timkiem.getText();
        int kq = 0;
        if (loaitk.equals("Loại sản phẩm")) {
            ++ soLoai;
            String maLoai = null;
            if (soLoai<10) {
                maLoai = "0" + soLoai;
            } else  maLoai = String.valueOf(soLoai);
            kq = loaiBLL.insertSelected(new LoaiSPDTO(maLoai, text, 1));
            
        } else if (loaitk.equals("Màu sắc")) {
            ++ soMau;
            String maMau = null;
            if (soMau<10) {
                maMau = "0" + soMau;
            } else  maMau = String.valueOf(soMau);
            kq = mauBLL.insertSelected(new MauSacDTO(maMau, text, 1));
            
        } else if (loaitk.equals("Kích thước")) {
            ++ soSize;
            String maSize = null;
            if (soSize<10) {
                maSize = "0" + soLoai;
            } else  maSize = String.valueOf(soLoai);
            kq = sizeBLL.insertSelected(new SizeDTO(maSize, text, 1));
        }
        if (kq != 0) {
            JOptionPane.showMessageDialog(null, "Thêm thành công!");
            jb_xemtatcaActionPerformed(evt);
        } else JOptionPane.showMessageDialog(null, "Thêm thất bại!");  
    }//GEN-LAST:event_jb_themActionPerformed

    private void jb_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_xoaActionPerformed
        String loaitk = (String) cb_timkiem.getSelectedItem();
        int kq = 0;
        if (loaitk.equals("Loại sản phẩm")) {
            int row = (int) tb_loai.getSelectedRow();
            if (row != -1) {
               String ma = (String) tb_loai.getValueAt(row, 0);
               kq = loaiBLL.deleteSelected(new LoaiSPDTO(ma));
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn loại sản phẩm cần xoá!");
            }
        } else if (loaitk.equals("Màu sắc")) {
            int row = (int) tb_mau.getSelectedRow();
            if (row != -1) {
               String ma = (String) tb_mau.getValueAt(row, 0);
               kq = mauBLL.deleteSelected(new MauSacDTO(ma));
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn màu cần xoá!");
            }
        } else if (loaitk.equals("Kích thước")) {
            int row = (int) tb_size.getSelectedRow();
            if (row != -1) {
               String ma = (String) tb_size.getValueAt(row, 0);
               kq = sizeBLL.deleteSelected(new SizeDTO(ma));
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn kích thước cần xoá!");
            }
        }
        if (kq != 0) {
            JOptionPane.showMessageDialog(null, "Xoá thành công!");
            jb_xemtatcaActionPerformed(evt);
        } else JOptionPane.showMessageDialog(null, "Xoá thất bại!");  
    }//GEN-LAST:event_jb_xoaActionPerformed

    private void jb_xemtatcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_xemtatcaActionPerformed
        docDuLieuMau();
        docDuLieuSize();
        docDuLieuLoaiSP();
    }//GEN-LAST:event_jb_xemtatcaActionPerformed

    private void cb_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_timkiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_timkiem;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jb_them;
    private javax.swing.JButton jb_timkiem;
    private javax.swing.JButton jb_xemtatca;
    private javax.swing.JButton jb_xoa;
    private javax.swing.JPanel jp_button;
    private javax.swing.JTable tb_loai;
    private javax.swing.JTable tb_mau;
    private javax.swing.JTable tb_size;
    private javax.swing.JTextField tf_timkiem;
    // End of variables declaration//GEN-END:variables
    
    private void docDuLieuLoaiSP() {
        ArrayList<LoaiSPDTO> list = loaiBLL.getSelectedAll();
        if (!list.isEmpty()) {
            for (LoaiSPDTO t : list) {
                Object[] data = new Object[]{t.getMaLoai(), t.getTenLoai()};
                model_loai.addRow(data);
                model_loai.fireTableDataChanged();
            }
        }
    }
    
    private void docDuLieuMau() {
        ArrayList<MauSacDTO> list = mauBLL.getSelectedAll();
        if (!list.isEmpty()) {
            for (MauSacDTO t : list) {
                Object[] data = new Object[]{t.getMaMau(), t.getTenMau()};
                model_mau.addRow(data);
                model_mau.fireTableDataChanged();
            }
        }
    }
    
    private void docDuLieuSize() {
        ArrayList<SizeDTO> list = sizeBLL.getSelectedAll();
        if (!list.isEmpty()) {
            for (SizeDTO t : list) {
                Object[] data = new Object[]{t.getMaSize(), t.getTenSize()};
                model_size.addRow(data);
                model_size.fireTableDataChanged();
            }
        }
    }
    
    
}
