/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanLiKho.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanLiKho.BLL.*;
import quanLiKho.DTO.NhaCungCapDTO;

/**
 *
 * @author PC
 */
public class NhaCungCapGUI extends javax.swing.JPanel {
    private NhaCungCapBLL nccBLL = new NhaCungCapBLL();
    private DefaultTableModel model;
    private String tenDN;
    
    private static int soNCC;
    
    public NhaCungCapGUI(String tenDN) {
        this.soNCC = nccBLL.getSelectedAll().size();
        model  = (DefaultTableModel) table.getModel();
        jButtonTimKiemAction jButtonTimKiemAction = new jButtonTimKiemAction();
        jButtonXemTCAction jButtonXemTCAction = new jButtonXemTCAction();
        this.jb_timkiem.addActionListener(jButtonTimKiemAction);
        this.jb_xemtatca.addActionListener(jButtonXemTCAction);
        docDuLieuNCC();
        this.tenDN = tenDN;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jp_timkiem = new javax.swing.JPanel();
        lb_masp1 = new javax.swing.JLabel();
        lb_masp5 = new javax.swing.JLabel();
        tf_diachi = new javax.swing.JTextField();
        lb_masp7 = new javax.swing.JLabel();
        lb_masp8 = new javax.swing.JLabel();
        tf_ten = new javax.swing.JTextField();
        tf_sdt = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        jb_them = new javax.swing.JButton();
        lb_masp2 = new javax.swing.JLabel();
        tf_ma = new javax.swing.JTextField();
        jb_xoa = new javax.swing.JButton();
        jb_sua = new javax.swing.JButton();
        jb_lammoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_timkiem = new javax.swing.JTextField();
        jb_xemtatca = new javax.swing.JButton();
        jb_timkiem = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1640, 940));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã NCC", "Tên NCC", "Số điện thoại", "Email", "Địa chỉ"
            }
        ));
        table.setRowHeight(35);
        jScrollPane13.setViewportView(table);

        jp_timkiem.setBackground(new java.awt.Color(255, 255, 255));
        jp_timkiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 26))); // NOI18N

        lb_masp1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lb_masp1.setText("Tên NCC:");

        lb_masp5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lb_masp5.setText("Địa chỉ:");

        tf_diachi.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tf_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_diachiActionPerformed(evt);
            }
        });

        lb_masp7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lb_masp7.setText("Số điện thoại:");

        lb_masp8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lb_masp8.setText("Email:");

        tf_ten.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tf_ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tenActionPerformed(evt);
            }
        });

        tf_sdt.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tf_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sdtActionPerformed(evt);
            }
        });

        tf_email.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        jb_them.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jb_them.setText("Thêm NCC");
        jb_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_themActionPerformed(evt);
            }
        });

        lb_masp2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lb_masp2.setText("Mã NCC:");

        tf_ma.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tf_ma.setEnabled(false);
        tf_ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_maActionPerformed(evt);
            }
        });

        jb_xoa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jb_xoa.setText("Xoá NCC");
        jb_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_xoaActionPerformed(evt);
            }
        });

        jb_sua.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jb_sua.setText("Cập nhật");
        jb_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_suaActionPerformed(evt);
            }
        });

        jb_lammoi.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jb_lammoi.setText("Làm mới");
        jb_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_lammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_timkiemLayout = new javax.swing.GroupLayout(jp_timkiem);
        jp_timkiem.setLayout(jp_timkiemLayout);
        jp_timkiemLayout.setHorizontalGroup(
            jp_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_timkiemLayout.createSequentialGroup()
                .addGroup(jp_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_timkiemLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_masp8))
                    .addGroup(jp_timkiemLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lb_masp2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_masp1)
                        .addGap(42, 42, 42)
                        .addComponent(tf_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(123, 123, 123)
                .addComponent(lb_masp5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jp_timkiemLayout.createSequentialGroup()
                .addGroup(jp_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_timkiemLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jb_them, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jb_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_timkiemLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(lb_masp7)
                        .addGap(37, 37, 37)
                        .addComponent(tf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249)
                        .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_timkiemLayout.setVerticalGroup(
            jp_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_timkiemLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jp_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_masp5)
                    .addComponent(tf_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_masp1)
                    .addComponent(lb_masp2)
                    .addComponent(tf_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jp_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_masp7)
                    .addComponent(tf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_masp8)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jp_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_them, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane13))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jp_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Tìm kiếm: ");

        tf_timkiem.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jb_xemtatca.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jb_xemtatca.setText("Xem tất cả");

        jb_timkiem.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jb_timkiem.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jb_xemtatca, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_xemtatca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_diachiActionPerformed
        int row = (int) table.getSelectedRow();
        if (row != -1) {
            tf_diachi.setText((String) table.getValueAt(row, 4));
        }
    }//GEN-LAST:event_tf_diachiActionPerformed

    private void tf_tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tenActionPerformed
        int row = (int) table.getSelectedRow();
        if (row != -1) {
            tf_diachi.setText((String) table.getValueAt(row, 1));
        }
    }//GEN-LAST:event_tf_tenActionPerformed

    private void tf_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sdtActionPerformed
        int row = (int) table.getSelectedRow();
        if (row != -1) {
            tf_diachi.setText((String) table.getValueAt(row, 2));
        }
    }//GEN-LAST:event_tf_sdtActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        int row = (int) table.getSelectedRow();
        if (row != -1) {
            tf_diachi.setText((String) table.getValueAt(row, 3));
        }
    }//GEN-LAST:event_tf_emailActionPerformed

    private void jb_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_themActionPerformed
        tf_ma.setText("");
        String ma = tf_ma.getText();
        String ten = tf_ten.getText();
        String diachi = tf_diachi.getText();
        int sdt = Integer.parseInt(tf_sdt.getText());
        String email = tf_email.getText();
        
        if (ma!= null || ten == null || diachi==null || email==null) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin!");
        } else {
            ++ soNCC;        
            if (soNCC<10) {
                ma = "0" + soNCC;
            } else  ma = String.valueOf(soNCC);
            NhaCungCapDTO ncc = new NhaCungCapDTO(ma, ten, diachi, email, sdt, 1);
            int kq = nccBLL.updateSelected(ncc);
            if (kq != 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
                docDuLieuNCC();
                jb_lammoiActionPerformed(evt);
            } else JOptionPane.showMessageDialog(null, "Thêm thất bại!");  
        }
    }//GEN-LAST:event_jb_themActionPerformed

    private void tf_maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_maActionPerformed
        int row = (int) table.getSelectedRow();
        if (row != -1) {
            tf_diachi.setText((String) table.getValueAt(row, 0));
        }
    }//GEN-LAST:event_tf_maActionPerformed

    private void jb_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_xoaActionPerformed
        int row = (int) table.getSelectedRow();
        if (row != -1) {
            String ma = (String) table.getValueAt(row, 0);
            int kq = nccBLL.deleteSelected(new NhaCungCapDTO(ma));
            if (kq != 0) {
                JOptionPane.showMessageDialog(null, "Xoá thành công!");
                docDuLieuNCC();
            } else JOptionPane.showMessageDialog(null, "Xoá thất bại!");  
        } else JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng cần xoá!");
    }//GEN-LAST:event_jb_xoaActionPerformed

    private void jb_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_suaActionPerformed
        String ma = tf_ma.getText();
        String ten = tf_ten.getText();
        String diachi = tf_diachi.getText();
        int sdt = Integer.parseInt(tf_sdt.getText());
        String email = tf_email.getText();
        
        if (ma== null || ten == null || diachi==null || email==null) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin!");
        } else {
            NhaCungCapDTO ncc = new NhaCungCapDTO(ma, ten, diachi, email, sdt, 1);
            int kq = nccBLL.updateSelected(ncc);
            if (kq != 0) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công!");
                docDuLieuNCC();
            } else JOptionPane.showMessageDialog(null, "Cập nhật thất bại!");  
        }
    }//GEN-LAST:event_jb_suaActionPerformed

    private void jb_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_lammoiActionPerformed
        tf_ma.setText("");
        tf_ten.setText("");
        tf_diachi.setText("");
        tf_sdt.setText("");
        tf_email.setText("");
        table.setSelectionMode(-1);
    }//GEN-LAST:event_jb_lammoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JButton jb_lammoi;
    private javax.swing.JButton jb_sua;
    private javax.swing.JButton jb_them;
    private javax.swing.JButton jb_timkiem;
    private javax.swing.JButton jb_xemtatca;
    private javax.swing.JButton jb_xoa;
    private javax.swing.JPanel jp_timkiem;
    private javax.swing.JLabel lb_masp1;
    private javax.swing.JLabel lb_masp2;
    private javax.swing.JLabel lb_masp5;
    private javax.swing.JLabel lb_masp7;
    private javax.swing.JLabel lb_masp8;
    private javax.swing.JTable table;
    private javax.swing.JTextField tf_diachi;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_ma;
    private javax.swing.JTextField tf_sdt;
    private javax.swing.JTextField tf_ten;
    private javax.swing.JTextField tf_timkiem;
    // End of variables declaration//GEN-END:variables
    
    private void docDuLieuNCC() {
        ArrayList<NhaCungCapDTO> list = nccBLL.getSelectedAll();
        if (!list.isEmpty()) {
            for (NhaCungCapDTO t : list) {
                Object[] data = new Object[]{t.getMaNCC(), t.getTenNCC(), t.getSdt(), t.getEmail(), t.getDiaChi()};
                model.addRow(data);
                model.fireTableDataChanged();
            }
        }
    }
    
    private class jButtonTimKiemAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
        
    }
    
    private class jButtonXemTCAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            docDuLieuNCC();
        }
        
    }
}
