/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanLiKho.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanLiKho.BLL.*;
import quanLiKho.DTO.*;

/**
 *
 * @author PC
 */
public class PhieuNhapGUI extends javax.swing.JPanel {
    
    private PhieuNhapBLL pnBLL = new PhieuNhapBLL();
    private CT_PhieuNhapBLL ctpnBLL = new CT_PhieuNhapBLL();
    private NhaCungCapBLL nccBLL = new NhaCungCapBLL();
    private TaiKhoanBLL tkBLL = new TaiKhoanBLL();
    private DefaultTableModel model;
    private String tenDN;
    private static int soPN;
    
    public PhieuNhapGUI(String tenDN) {
        this.soPN = pnBLL.getSelectedAll().size();
        this.tenDN = tenDN;
        initComponents();
        model = (DefaultTableModel) tb_pn.getModel();
        loadDataIntoTable();
        jButtonHuyPhieuAction jButtonHuyPhieuAction = new jButtonHuyPhieuAction();
        jButtonTimKiemAction jButtonTimKiemAction = new jButtonTimKiemAction();
        jButtonXemCTAction jButtonXemCTAction = new jButtonXemCTAction();
        jButtonXemTCAction jButtonXemTCAction = new jButtonXemTCAction();
        this.jb_huyphieu.addActionListener(jButtonHuyPhieuAction);
        this.jb_timkiem.addActionListener(jButtonTimKiemAction);
        this.jb_xemtatca.addActionListener(jButtonXemTCAction);
        this.jb_xemct.addActionListener(jButtonXemCTAction);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jb_xemct = new javax.swing.JButton();
        jb_huyphieu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pn = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        cb_maphieu = new javax.swing.JComboBox<>();
        cb_ncc = new javax.swing.JComboBox<>();
        jb_timkiem = new javax.swing.JButton();
        cb_nv = new javax.swing.JComboBox<>();
        jb_xemtatca = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1640, 940));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jb_xemct.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jb_xemct.setText("Xem chi tiết");

        jb_huyphieu.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jb_huyphieu.setText("Huỷ phiếu");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(638, 638, 638)
                .addComponent(jb_xemct)
                .addGap(137, 137, 137)
                .addComponent(jb_huyphieu)
                .addContainerGap(531, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_xemct)
                    .addComponent(jb_huyphieu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tb_pn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tb_pn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Nhà cung cấp", "Nhân viên nhập", "Thời gian", "Tổng tiền"
            }
        ));
        tb_pn.setRowHeight(40);
        jScrollPane1.setViewportView(tb_pn);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel1.setText("Mã phiếu");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel2.setText("Nhà cung cấp");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel3.setText("Từ ngày");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel4.setText("Nhân viên nhập");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel5.setText("Đến ngày");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel6.setText("Từ số tiền (VNĐ)");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel7.setText("Đến số tiền (VNĐ)");

        cb_maphieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_maphieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_maphieuActionPerformed(evt);
            }
        });

        cb_ncc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_ncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nccActionPerformed(evt);
            }
        });

        jb_timkiem.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jb_timkiem.setText("Tìm kiếm");

        cb_nv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nvActionPerformed(evt);
            }
        });

        jb_xemtatca.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jb_xemtatca.setText("Xem tất cả");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_maphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(34, 34, 34)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(jb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(cb_ncc, 0, 233, Short.MAX_VALUE)
                                .addGap(141, 141, 141)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jb_xemtatca, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(cb_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_maphieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_xemtatca, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(854, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_maphieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_maphieuActionPerformed
        ArrayList<PhieuNhapDTO> phieunhap = pnBLL.getSelectedAll();
        ArrayList<String> listPN = new ArrayList<>();
        //listDS.add("");    
        for (PhieuNhapDTO pn : phieunhap) {
            listPN.add(pn.getMaPhieu());
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(listPN.toArray(new String[0]));
        cb_maphieu.setModel(model);
    }//GEN-LAST:event_cb_maphieuActionPerformed

    private void cb_nccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nccActionPerformed
        ArrayList<NhaCungCapDTO> ncc = nccBLL.getSelectedAll();
        ArrayList<String> listNCC = new ArrayList<>();
        //listDS.add("");    
        for (NhaCungCapDTO t : ncc) {
            listNCC.add(t.getTenNCC());
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(listNCC.toArray(new String[0]));
        cb_ncc.setModel(model);
    }//GEN-LAST:event_cb_nccActionPerformed

    private void cb_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nvActionPerformed
        ArrayList<PhieuNhapDTO> phieunhap = pnBLL.getSelectedAll();
        
        ArrayList<String> listPN = new ArrayList<>();
        //listDS.add("");    
        for (PhieuNhapDTO pn : phieunhap) {
            TaiKhoanDTO tk = tkBLL.getSelectedById(new TaiKhoanDTO(pn.getMaTK()));
            listPN.add(tk.getTenDN());
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(listPN.toArray(new String[0]));
        cb_nv.setModel(model);
    }//GEN-LAST:event_cb_nvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_maphieu;
    private javax.swing.JComboBox<String> cb_ncc;
    private javax.swing.JComboBox<String> cb_nv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton jb_huyphieu;
    private javax.swing.JButton jb_timkiem;
    private javax.swing.JButton jb_xemct;
    private javax.swing.JButton jb_xemtatca;
    private javax.swing.JTable tb_pn;
    // End of variables declaration//GEN-END:variables

    public void loadDataIntoTable() {
        ArrayList<PhieuNhapDTO> list = pnBLL.getSelectedAll();
        if (!list.isEmpty()) {
            for (PhieuNhapDTO pn : list) {
                TaiKhoanDTO tk = tkBLL.getSelectedById(new TaiKhoanDTO(pn.getMaTK()));
                NhaCungCapDTO ncc = nccBLL.getSelectedById(new NhaCungCapDTO(pn.getMaNCC()));
                Object[] data = new Object[]{pn.getMaPhieu(), ncc.getTenNCC(), tk.getTenDN(), pn.getNgayTao(), pn.getTongTien()};
                model.addRow(data);
                model.fireTableDataChanged();
            }
        }
    }
   
    private class jButtonHuyPhieuAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            int row = tb_pn.getSelectedRow();
            if (row != -1) {
                int check = JOptionPane.showConfirmDialog(null,
                        "Bạn chắc chắn muốn xóa không ?", "Xác nhận",
                        JOptionPane.YES_NO_OPTION);
                if (check == JOptionPane.YES_OPTION) {
                    String maPhieu = (String) tb_pn.getValueAt(row, 0);           
                    int dong = pnBLL.deleteSelected(new PhieuNhapDTO(maPhieu));
                    if (dong != 0) {
                       JOptionPane.showMessageDialog(null, "Huỷ phiếu thành công!"); 
                       loadDataIntoTable();
                    } else {
                        JOptionPane.showMessageDialog(null, "Huỷ phiếu thất bại!");
                    } 
                }
            } else {
                JOptionPane.showMessageDialog(null,
                        "Vui lòng, chọn dòng dữ liệu cần xóa !!!");
            }
        }      
    }
    
    private class jButtonXemCTAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            new CT_PhieuNhapGUI();
        }
        
    }
    
    private class jButtonTimKiemAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
        
    }
    
    private class jButtonXemTCAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            loadDataIntoTable();
        }
        
    }
}
