/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanLiKho.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanLiKho.BLL.*;
import quanLiKho.DTO.*;

/**
 *
 * @author PC
 */
public class ThemPhieuNhapGUI extends javax.swing.JPanel {
    private LoaiSPBLL loaiBLL = new LoaiSPBLL();
    private MauSacBLL mauBLL = new MauSacBLL();
    private SizeBLL sizeBLL = new SizeBLL();
    private PhieuNhapBLL pnBLL = new PhieuNhapBLL();
    private CT_PhieuNhapBLL ctpnBLL = new CT_PhieuNhapBLL();
    private NhaCungCapBLL nccBLL = new NhaCungCapBLL();
    private TaiKhoanBLL tkBLL = new TaiKhoanBLL();
    private SanPhamBLL spBLL = new SanPhamBLL();
    private CT_SanPhamBLL ctspBLL = new CT_SanPhamBLL();
    private DefaultTableModel model_sp, model_ctsp;
    private String tenDN;
    private static int soPN;
    private ArrayList<CT_PhieuNhapDTO> listctpn = new ArrayList<>();
    
    public ThemPhieuNhapGUI(String tenDN) {
        jButtonTimKiemAction jButtonTimKiemAction = new jButtonTimKiemAction();
        jButtonThemAction jButtonThemAction = new jButtonThemAction();
        jButtonXoaAction jButtonXoaAction = new jButtonXoaAction();
        jButtonNhapAction jButtonNhapAction = new jButtonNhapAction();
        this.jb_timkiem.addActionListener(jButtonTimKiemAction);
        this.jb_themsp.addActionListener(jButtonThemAction);
        this.jb_xoasp.addActionListener(jButtonXoaAction);
        this.jb_nhapkho.addActionListener(jButtonNhapAction);
        model_sp  = (DefaultTableModel) tb_sp.getModel();
        model_ctsp  = (DefaultTableModel) tb_ctsp.getModel();
        this.soPN = pnBLL.getSelectedAll().size();
        this.tenDN = tenDN;
        initComponents();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar calendar = Calendar.getInstance();
        String ngay = dateFormat.format(calendar.getTimeInMillis());
        Date ngayTao = java.sql.Date.valueOf(ngay);
        tf_ngayTao.setText(ngay);       
        tf_nv.setText(tenDN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_sp = new javax.swing.JTable();
        jb_timkiem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ctsp = new javax.swing.JTable();
        cb_ncc = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_size = new javax.swing.JComboBox<>();
        cb_mau = new javax.swing.JComboBox<>();
        jSpinner_sl = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_ngayTao = new javax.swing.JTextField();
        tf_nv = new javax.swing.JTextField();
        tf_tongtien = new javax.swing.JTextField();
        jb_nhapkho = new javax.swing.JButton();
        jb_themsp = new javax.swing.JButton();
        jb_xoasp = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tf_gia = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1640, 940));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tb_sp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tb_sp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(tb_sp);

        jb_timkiem.setText("Tìm kiếm");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setText("Màu sắc");

        tb_ctsp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tb_ctsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Màu sắc", "Size", "Đơn giá", "Số lượng"
            }
        ));
        tb_ctsp.setRowHeight(35);
        jScrollPane1.setViewportView(tb_ctsp);

        cb_ncc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_ncc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        cb_ncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nccActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Kích cỡ");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setText("Số lượng");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setText("Nhà cung cấp ");

        cb_size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_size.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        cb_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sizeActionPerformed(evt);
            }
        });

        cb_mau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_mau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        cb_mau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mauActionPerformed(evt);
            }
        });

        jSpinner_sl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setText("Ngày tạo");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("Tổng tiền (VNĐ)");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setText("Nhân viên nhập");

        tf_ngayTao.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        tf_ngayTao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        tf_nv.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        tf_nv.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        tf_tongtien.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        tf_tongtien.setText("0");
        tf_tongtien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        jb_nhapkho.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jb_nhapkho.setText("Nhập kho");

        jb_themsp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jb_themsp.setText("Thêm sản phẩm");

        jb_xoasp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jb_xoasp.setText("Xoá sản phẩm");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setText("Giá nhập");

        tf_gia.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        tf_gia.setText("0");
        tf_gia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jb_themsp, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_xoasp, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 636, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(41, 41, 41)
                .addComponent(tf_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_mau, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_size, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSpinner_sl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_gia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ncc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngayTao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_nhapkho)
                .addGap(641, 641, 641))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tf_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jb_themsp)
                                    .addComponent(jb_xoasp)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(cb_mau, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(cb_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cb_size, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel11)
                                                .addComponent(jSpinner_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tf_ngayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jb_nhapkho)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_nccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nccActionPerformed
        ArrayList<NhaCungCapDTO> ncc = nccBLL.getSelectedAll();
        ArrayList<String> listNCC = new ArrayList<>();
        //listDS.add("");    
        for (NhaCungCapDTO t : ncc) {
            listNCC.add(t.getTenNCC());
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(listNCC.toArray(new String[0]));
        cb_ncc.setModel(model);
    }//GEN-LAST:event_cb_nccActionPerformed

    private void cb_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sizeActionPerformed
        ArrayList<SizeDTO> size = sizeBLL.getSelectedAll();
        ArrayList<String> list = new ArrayList<>();
        //listDS.add("");    
        for (SizeDTO t : size) {
            list.add(t.getTenSize());
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(list.toArray(new String[0]));
        cb_size.setModel(model);
    }//GEN-LAST:event_cb_sizeActionPerformed

    private void cb_mauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mauActionPerformed
        ArrayList<MauSacDTO> mau = mauBLL.getSelectedAll();
        ArrayList<String> list = new ArrayList<>();
        //listDS.add("");    
        for (MauSacDTO t : mau) {
            list.add(t.getTenMau());
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(list.toArray(new String[0]));
        cb_mau.setModel(model);
    }//GEN-LAST:event_cb_mauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_mau;
    private javax.swing.JComboBox<String> cb_ncc;
    private javax.swing.JComboBox<String> cb_size;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_sl;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb_nhapkho;
    private javax.swing.JButton jb_themsp;
    private javax.swing.JButton jb_timkiem;
    private javax.swing.JButton jb_xoasp;
    private javax.swing.JTable tb_ctsp;
    private javax.swing.JTable tb_sp;
    private javax.swing.JTextField tf_gia;
    private javax.swing.JTextField tf_ngayTao;
    private javax.swing.JTextField tf_nv;
    private javax.swing.JTextField tf_tongtien;
    // End of variables declaration//GEN-END:variables
    
    public void loadDataIntoTable() {
        ArrayList<SanPhamDTO> list = spBLL.getSelectedAll();
        if (!list.isEmpty()) {
            for (SanPhamDTO sp : list) {
                Object[] data = new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getSoLuong()};
                model_sp.addRow(data);
                model_sp.fireTableDataChanged();
            }
        }
    }
    
    private class jButtonTimKiemAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
        
    }
    
    private class jButtonThemAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
             int row = (int) tb_sp.getSelectedRow();
             if (row != -1) {
                 String ma = (String) tb_sp.getValueAt(row, 0);
                 String mau = (String) cb_mau.getSelectedItem();
                 String size = (String) cb_size.getSelectedItem();
                 int soLuong = (int) jSpinner_sl.getValue();
                 int gia = Integer.parseInt(tf_gia.getText());
                 
                 
             } else {
                 JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm cần nhập!!!");
             }
            
            
            
        }
        
    }
    
    private class jButtonXoaAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            
        }
        
    }
    
    private class jButtonNhapAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {                   
            
        }
        
    }

}
