/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package muaHang;


import static java.nio.file.Files.size;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.*;

/**
 *
 * @author truon
 */
public class chiTietSP extends javax.swing.JFrame {
  static Connection con = MyConnection.getConnection();
  String MASP,MAKH;
     
    /**
     * Creates new form chiTietSP
     */
    public chiTietSP(String MASP,String MAKH) {
        this.MAKH=MAKH;
        this.MASP=MASP;
        initComponents();
        ctSp(MASP);
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcbbMau = new javax.swing.JComboBox<>();
        jcbbSize = new javax.swing.JComboBox<>();
        them = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setTitle("Chân váy ngắn xếp ly xòe");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jcbbMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbMauActionPerformed(evt);
            }
        });

        jcbbSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbSizeActionPerformed(evt);
            }
        });

        them.setBackground(new java.awt.Color(255, 51, 102));
        them.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        them.setText("Thêm vào giỏ hàng");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText(" 200000 ");

        jLabel2.setText("Chọn màu");

        jLabel3.setText("Chọn size");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 2, 1));

        jLabel4.setText("Số lượng");

        jLabel6.setText("Giá");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("vnđ");

        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jcbbMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jcbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbbMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(them)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        try  {
             int soluong=((int) jSpinner1.getValue());
            String query = "{CALL themvaogiohang(?,?,?,?,?)}";
            CallableStatement stmt = con.prepareCall(query);
            
            stmt.setString(1, getMactsp());
            stmt.setString(2,jLabel8.getText());//ten
        
            stmt.setInt(3, soluong);//soluong
            int gia=Integer.parseInt(jLabel1.getText());
            
            stmt.setInt(4,gia);
            stmt.setString(5,MAKH);
            // Execute the stored procedure
            stmt.execute();
            System.out.println("them thanh cong");
            // Process the result set
           
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_themActionPerformed

    private void jcbbSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbbSizeActionPerformed

    private void jcbbMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbMauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbbMauActionPerformed

    /**
     * @param args the command line arguments
     */
     public void ctSp(String temp){   
         String sql="SELECT TENSP,GIABAN,HINHANH,ctsp.SOLUONG,TENSIZE,TENMAU,MACTSP,SP.MASP\n" +
"FROM SANPHAM sp,CT_SANPHAM ctsp,SIZE s,MAUSAC m\n" +
"where sp.MASP=ctsp.MASP and ctsp.MAMAU=m.MAMAU and s.MASIZE=ctsp.MASIZE\n" +
"AND SP.MASP='"+temp+"'";
         List<String> mau = new ArrayList<>();
         List<String> size = new ArrayList<>();
        try{    
  
              Statement stmt=con.createStatement();
    ResultSet rs = stmt.executeQuery(sql);
     while(rs.next())  {
          {
         String ten=rs.getString(1);
         String gia=rs.getString(2);
      
   
         jLabel5.setIcon(new ImageIcon(getClass().getResource("/img/"+rs.getString(3)+"/"))); // NOI18N
          setTitle(ten);
          jLabel8.setText(ten);
          jLabel8.setVisible(false);
          jLabel1.setText(gia);
        size.add(rs.getString(5));
         mau.add(rs.getString(6));
             
         } 
     }
     
     List<String> size2 = size.stream()
                .distinct()
                .collect(Collectors.toList());
      List<String> mau2 = mau.stream()
                .distinct()
                .collect(Collectors.toList());
  
     
          for(String i:size2){
              jcbbSize.addItem(i);
          }
          for(String i:mau2){
              jcbbMau.addItem(i);
          }
          String a=getMactsp();
           
     

    

      
         
    
     

        
     }
        
          
 catch(Exception e){ 
System.out.println(e);
    }
     }
     public String getMactsp(){
         String size= (String) jcbbSize.getSelectedItem();
         String mau=(String) jcbbMau.getSelectedItem();
         String mactsp="";
        // if(MASP+size+mau)
        String sql="SELECT TENSP,ctsp.SOLUONG,TENSIZE,TENMAU,MACTSP,SP.MASP,m.MAMAU,s.MASIZE\n" +
"FROM SANPHAM sp,CT_SANPHAM ctsp,SIZE s,MAUSAC m\n" +
"where sp.MASP=ctsp.MASP and ctsp.MAMAU=m.MAMAU and s.MASIZE=ctsp.MASIZE\n" +
"AND SP.MASP='"+MASP+"'"+
               "AND TENSIZE='"+size+"'"+
"AND TENMAU='"+mau+"'";
       
        try{    
  
              Statement stmt=con.createStatement();
              ResultSet rs = stmt.executeQuery(sql);

              while(rs.next()){
                   mactsp=rs.getString("MACTSP");            
                         int max=rs.getInt(2);
      jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, max, 1));    
                    
                  
              }
     }
         catch(Exception e){ 
System.out.println(e);
    }
         return mactsp;
     }
    //
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                chiTietSP a=new chiTietSP("S00001","b");
                a.setVisible(true);
                  a.setLocationRelativeTo(null);
                  a.setSize(550, 400);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> jcbbMau;
    private javax.swing.JComboBox<String> jcbbSize;
    private javax.swing.JButton them;
    // End of variables declaration//GEN-END:variables
}
