/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package muaHang;

import java.sql.CallableStatement;
import static muaHang.gioHang.con;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static muaHang.gioHang.con;

/**
 *
 * @author truon
 */
public class lsMuaHang extends javax.swing.JInternalFrame {

    /**
     * 
     * Creates new form lsMuaHang
     */  public String matk;
      static Connection con = MyConnection.getConnection();
         PreparedStatement ps;
    public lsMuaHang(String matk) {
        this.matk=matk;
        initComponents();
        getLSmuahang(jTable1,matk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBorder(null);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ ĐƠN HÀNG", "GIÁ", "PT THANH TOÁN", "THỜI GIAN", "TÌNH TRẠNG XỬ LÝ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("XÓA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(727, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           int select = jTable1.getSelectedRow();
            String madh = (String) jTable1.getValueAt(select, 0);
            String tt = (String) jTable1.getValueAt(select, 4);
           try {
              String query = "{CALL xoa_dh(?)(?)}";
            CallableStatement stmt;
              stmt = con.prepareCall(query);
              stmt.setString(1, madh);
              stmt.setString(2, tt);
              stmt.execute();
              System.out.println("xoa thanh cong");
          } catch (SQLException ex) {
              Logger.getLogger(gioHang.class.getName()).log(Level.SEVERE, null, ex);
          }

                
       
    }//GEN-LAST:event_jButton1ActionPerformed
     public void getLSmuahang(JTable table, String matk) {
        String sql = "SELECT * FROM DONHANG WHERE MATK="+matk;
         
        try {
                Statement stmt=con.createStatement();
               
            ResultSet rs = stmt.executeQuery(sql);
          
        
    
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            Object[] row;
            while (rs.next()) {
             
                row = new Object[5];        
                row[0] = rs.getString(1);
                row[1] = rs.getInt(3);
                row[2] = rs.getString(4);
                row[3] = rs.getString(5);
                if (rs.getInt(6) == 2) 
                    row[4] = "Đã duyệt";
                if (rs.getInt(6) == 1) 
                    row[4] = "Chưa duyệt";
                else 
                    row[4] = "Chưa thanh toán";
                
                model.insertRow(0, row);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(lsMuaHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
