/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package muaHang;
import static muaHang.TrangChu.con;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author truon
 */
public class sanPham extends javax.swing.JInternalFrame {

    Connection con = MyConnection.getConnection();
    PreparedStatement ps;

    /**
     * Creates new form sanPham
     */
    public sanPham() {
        initComponents();
        xuatsp("");
      //  xuatsp2("");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(86, 72));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filter.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1848, 1848, 1848))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1787, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 15, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 15, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String search=jTextField1.getText();
        jPanel2.removeAll();
        jPanel2.removeAll();
        xuatsp(search);
      /*  if(search.isEmpty()){
            xuatsp("");
        }
        else xuatsp(search);*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
  
    public void xuatsp(String search){
        String sql="SELECT TenSp,GiaBan,HinhAnh,MaSP FROM SanPham sp where concat(tensp,giaban) like ?";
       
         JButton buttons;
        JPanel pn;
        JLabel lb;
        try{      
            ps = con.prepareStatement(sql);
            ps.setString(1, "%" + search + "%");
            ResultSet rs = ps.executeQuery();
     while(rs.next())  {
         
         String ten=rs.getString(1);
         String gia=rs.getString(2)+"vnđ";
         String hinh="/img/"+rs.getString(3)+"/";
        
         String ma=rs.getString(4);
         pn=new JPanel();
         pn.setLayout(new java.awt.BorderLayout());
         //HINHANH
        buttons=new JButton();
         buttons.setIcon(new ImageIcon(getClass().getResource("/img/"+rs.getString(3)+"/"))); // NOI18N
    //  buttons.setIcon(new ImageIcon(getClass().getResource("/img/"+"S00006.png"+"/"))); // NOI18N
         //TENSP
         lb=new JLabel(ten);
            lb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            lb.setBackground(new java.awt.Color(0, 0, 0));
         pn.add(lb,java.awt.BorderLayout.PAGE_START);
         //GIASP
          lb=new JLabel(gia);
         lb.setFont(new java.awt.Font("Segoe UI", 0, 18));
           lb.setForeground(new java.awt.Color(255, 0, 0));
         pn.setBackground(new java.awt.Color(255, 255, 255));
         pn.add(buttons,java.awt.BorderLayout.CENTER);    
         pn.add(lb,java.awt.BorderLayout.PAGE_END);
          pn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
           //buttons.setPreferredSize(new java.awt.Dimension(50, 72));
         jPanel2.add(pn);
          buttons.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                       chiTietSP a=new chiTietSP(ma,"1");
                a.setVisible(true);
                  a.setLocationRelativeTo(null);
                  a.setSize(550, 400);
                }
            });
  
     }
          
} catch(Exception e){ 
System.out.println(e);
    }
    }
    public void xuatsp2(String search){
        String sql="SELECT TenSp,GiaBan,HinhAnh,MaSP FROM SanPham sp";
        
        try{      
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            JButton buttons;
        JPanel pn;
        JLabel lb;
        int i=0;
     while(rs.next())  {
         if(i==7) break;
         i++;
         String ten=rs.getString(1);
         String gia=rs.getString(2)+"vnđ";
         String hinh="/img/"+rs.getString(3)+"/";
       
         String ma=rs.getString(4);
         pn=new JPanel();
         pn.setLayout(new java.awt.BorderLayout());
         //HINHANH
        buttons=new JButton();
         buttons.setIcon(new ImageIcon(getClass().getResource("/img/"+rs.getString(3)+"/"))); // NOI18N
    //  buttons.setIcon(new ImageIcon(getClass().getResource("/img/"+"S00006.png"+"/"))); // NOI18N
         //TENSP
         lb=new JLabel(ten);
            lb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            lb.setBackground(new java.awt.Color(0, 0, 0));
         pn.add(lb,java.awt.BorderLayout.PAGE_START);
         //GIASP
          lb=new JLabel(gia);
         lb.setFont(new java.awt.Font("Segoe UI", 0, 18));
           lb.setForeground(new java.awt.Color(255, 0, 0));
         pn.setBackground(new java.awt.Color(255, 255, 255));
         pn.add(buttons,java.awt.BorderLayout.CENTER);    
         pn.add(lb,java.awt.BorderLayout.PAGE_END);
          pn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
           //buttons.setPreferredSize(new java.awt.Dimension(50, 72));
         jPanel2.add(pn);
          buttons.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                       chiTietSP a=new chiTietSP(ma,"1");
                a.setVisible(true);
                  a.setLocationRelativeTo(null);
                  a.setSize(550, 400);
                }
            });
  
     }
          
} catch(Exception e){ 
System.out.println(e);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
